### ISSUE TITLE
Error starting GhostDriver

### ISSUE THREAD

**Issue by mgbellaire** [xolvio/meteor-webdriver#17]
Starting up meteor with VELOCITY_DEBUG=1 because PhantomJS was failing for some reason. This is the last error to show up in the console log.

```
[xolvio:webdriver][phantom output] [ERROR - 2015-01-25T19:18:48.554Z] GhostDriver - main.fail - {"message":"Could not start Ghost Driver","line":82,"sourceId":169186800,"sourceURL":":/ghostdriver/main.js","stack":"Error: Could not start Ghost Driver\n    at :/ghostdriver/main.js:82","stackArray":[{"sourceURL":":/ghostdriver/main.js","line":82}]}
```

Need anymore info?

**Comment by mgbellaire** [comment]
I am also getting some weird error that says that Phantom is running, but I am not seeing any running processes for phantom.

It just gives me this plain and simple error: `[xolvio:webdriver] Phantom is already running, not starting a new one`

**Comment by mgbellaire** [comment]
Sorry, Sam. :( I was getting these errors because I didn't add the callback(); to the end of a step definition. *face_palm*

**Comment by samhatoum** [comment]
Glad you found it!

I'm going to add a default  timeout on step defs soon

**Comment by mgbellaire** [comment]
Glad this was still useful. I am starting to use Webdriver with Cucumber.JS in Meteor. It's the bomb!
