### ISSUE TITLE
Hangs when phantom is not present (codeship / ci)

### ISSUE THREAD

**Issue by samhatoum** [xolvio/meteor-webdriver#18]
Should timeout and log the error

**Comment by queso** [comment]
rof@railsonfire_2abbd2b0-8d61-0132-89a0-16937fb8959d_8ce12098136b:~/clone$ /home/rof/.meteor/packages/xolvio_webdriver/.0.1.8.1m78m6c++os+web.browser+web.cordova/npm/node_modules/phantomjs/lib/phantom/bin/phantomjs
-bash: /home/rof/.meteor/packages/xolvio_webdriver/.0.1.8.1m78m6c++os+web.browser+web.cordova/npm/node_modules/phantomjs/lib/phantom/bin/phantomjs: cannot execute binary file: Exec format error

**Comment by queso** [comment]
Actually, it isn't an error with phantom not being there, it is an issue with the bundled phantom being the wrong format.

**Comment by samhatoum** [comment]
got a solution?

**Comment by queso** [comment]
don't ship with pre-compiled binaries?

**Comment by queso** [comment]
if you relied directly on the phantomjs package instead for it, wouldn't that get the build server to pick up and include the right platforms for you?

**Comment by queso** [comment]
It looks like you do rely on phantomjs... Did you do the publish-for-arch stuff for x64 linux?

**Comment by samhatoum** [comment]
hmmmm, no I haven't! what a great idea :D

**Comment by queso** [comment]
If I am a package admin, I think I can do it...

**Comment by queso** [comment]
Turns out that wasn't the issue, need to investigate more. For now I am trying to manually install and run phantom.js and use that version to run my tests.

**Comment by samhatoum** [comment]
fixed by #21?

**Comment by queso** [comment]
#21 allows you to fix it, but I still think the hanging should stop, we should detect that the phantom process didn't kick off and exit the test run...

**Comment by queso** [comment]
This problem is weird because it lives between two code bases.. Who is responsible for making sure phantom started? Cucumber or Webdriver?

**Comment by samhatoum** [comment]
Webdriver has a phantom manager. When using the getGhostDriver method, it
should handle all edge cases. When being over-ridden with PHANTOM_PATH then
it's down to whatever is starting (probably not cucumber, more likely a
script)

**Comment by queso** [comment]
I think maybe you misunderstand the point of PHANTOM_PATH. You are just providing the location of the phantom executable on the box so that the spawner can still do it's work.

The issue here is when the long spawner tries to spawn, if it doesn't start up, nothing bad happens...

**Comment by samhatoum** [comment]
Gotcha. In that case, the buck still stops with webdriver for starting
phantom.

There will be another use-case for phantom already being started. In this
case, a webdriver remote can be created. Think private selenium-grid and
sauce-labs. In this case, it's already supported in that you just don't
have to use getGhostDriver, and instead you use wdio.instance.remote()

**Comment by samhatoum** [comment]
the latest webdriver should have this fixed

**Comment by samhatoum** [comment]
Please reopen if not
