### ISSUE TITLE
can't execute phantomJs on CircleCI

### ISSUE THREAD

**Issue by hexsprite** [xolvio/meteor-webdriver#23]
Kinda related to other issues but this is more specific

I noticed that phantomjs would not start on Circle CI because the executable was not compatible with the arch.  (mach-o i386)

What's odd is that meteor-tool also installs phantomjs (could we just use that instead of downloading it twice??) but it the proper arch  (ELF 64-bit LSB executable)

For whatever reason phantomjs npm for xolvio:webdriver is not downloading the correct executable when running on CircleCI 

```
./packages/xolvio_webdriver/.0.2.1.kj2el4++os+web.browser+web.cordova/npm/node_modules/phantomjs/lib/phantom/bin/phantomjs: Mach-O executable i386
./packages/meteor-tool/.1.0.40.1ef5dzv++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.9, stripped
```

**Comment by samhatoum** [comment]
sorry for long replies, I've been away

I've noticed this also. @queso [made a change](https://github.com/xolvio/meteor-webdriver/commit/028329302ae3bd66a76028dd06600c8568054815) that allows you to pass in a `PHANTOM_PATH`. I'm trying to figure out the meteor-tools path and to use that instead - that is the right approach I think

**Comment by queso** [comment]
I am not sure it is right approach. The better approach would be to figure out why the npm phantom package isn't grabbing the right binary. Or make cucumber crap out when phantom doesn't start.

**Comment by samhatoum** [comment]
agreed, the getGhostDriver should have a timeout rather than linger forever.

I do recall something to do with having to run the process as a node process on linux boxes as opposed to a binary. I'll try to mess with that.

**Comment by samhatoum** [comment]
should be fixes in latest
