### ISSUE TITLE
Support for chromedriver

### ISSUE THREAD

**Issue by hexsprite** [xolvio/meteor-webdriver#25]
Here's how I got chromedriver working.  First I installed it with homebrew: `brew install chromedriver`

Then I changed my world.coffee like so:

```
  @World = (next) ->
    helper.world = this
    helper.world.cucumber = Package['xolvio:cucumber'].cucumber
    wdio = Package['xolvio:webdriver'].wdio.instance
    options =
      host: "localhost"
      port: 9515
      desiredCapabilities:
        browserName: 'chrome'
    helper.world.browser = wdio.remote(options)
    next()
```

Then I started chromedriver:  `chromedriver --url-base=/wd/hub`

At the very least we could add this to a README, if not add some package support ala getChromedriver()

**Comment by samhatoum** [comment]
Defo
