### ISSUE TITLE
Tests won't complete on initial run of meteor with PHANTOM_PATH

### ISSUE THREAD

**Issue by nathanathan** [xolvio/meteor-webdriver#28]
I have to restart the meteor process once for all my tests to complete. What I think is happening is https://github.com/xolvio/meteor-webdriver/issues/26 causing the tests to hang, but when I restart meteor the zombie process from https://github.com/xolvio/meteor-webdriver/issues/27 somehow avoids the bug that is causing https://github.com/xolvio/meteor-webdriver/issues/26.

**Comment by samhatoum** [comment]
Should be fixed in latest, let me know if not
