### ISSUE TITLE
Windows 8.1 Big error

### ISSUE THREAD

**Issue by cannap** [xolvio/meteor-webdriver#37]
HI i got this error when i try to start meteor with this package
http://laravel.io/bin/42m3X

Packagelist
accounts-base@1.2.0
accounts-meteor-developer@1.0.4
accounts-oauth@1.1.5
accounts-password@1.1.1
accounts-ui@1.1.5
accounts-ui-unstyled@1.1.7
alanning:roles@1.2.13
aldeed:autoform@5.1.2
aldeed:collection2@2.3.3
aldeed:simple-schema@1.3.2
aldeed:template-extension@3.4.3
amplify@1.0.0
autoupdate@1.2.1
babrahams:editable-json@0.4.3
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
cannap:highlightmark@0.0.1
check@1.0.5
chrismbeckett:toastr@2.1.0
chuangbo:cookie@1.1.0
coffeescript@1.0.6
dburles:mongo-collection-instances@0.3.3
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
email@1.0.6
fastclick@1.0.3
fourseven:scss@2.1.1
geojson-utils@1.0.3
gwendall:session-json@0.1.7
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
insecure@1.0.3
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7
jameslefrere:irc@0.1.0
jquery@1.11.3_2
json@1.0.3
kevohagan:sweetalert@0.5.0
lai:collection-extensions@0.1.3
launch-screen@1.0.2
less@1.0.14
livedata@1.0.13
localstorage@1.0.3
logging@1.0.7
manuelschoebel:ms-seo@0.4.1
markdown@1.0.4
matb33:collection-hooks@0.7.11
meteor@1.1.6
meteor-developer@1.1.3
meteor-platform@1.2.2
meteorhacks:fast-render@2.3.2
meteorhacks:inject-data@1.2.3
meteorhacks:picker@1.0.2
meteorhacks:search-source@1.3.0
meteorhacks:subs-manager@1.3.0
meteortoys:toykit@0.3.4
mike:mocha@0.5.3-rc.1
minifiers@1.1.5
minimongo@1.0.8
mobile-status-bar@1.0.3
momentjs:moment@2.10.2
mongo@1.1.0
mrt:nprogress@0.1.0
msavin:jetsetter@1.0.11
msavin:mongol@1.0.22
npm-bcrypt@0.7.8_2
oauth@1.1.4
oauth2@1.1.3
observe-sequence@1.0.6
ongoworks:security@1.1.0
ordered-dict@1.0.3
package-version-parser@3.0.3
pagebakers:ionicons@2.0.0
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
sanjo:long-running-child-process@1.0.3
sanjo:meteor-files-helpers@1.1.0_4
sanjo:meteor-version@1.0.0
semantic:ui-button@1.11.7
semantic:ui-divider@1.11.7
semantic:ui-dropdown@1.11.7
semantic:ui-form@1.11.7
semantic:ui-label@1.11.7
semantic:ui-message@1.11.7
semantic:ui-transition@1.11.7
service-configuration@1.0.4
session@1.1.0
settinghead:auto-nprogress@1.0.0
sha@1.0.3
softwarerero:accounts-t9n@1.0.9
spacebars@1.0.6
spacebars-compiler@1.0.6
spiderable@1.0.7
srp@1.0.3
templating@1.1.1
tinytest@1.0.5
tracker@1.0.7
ui@1.0.6
underscore@1.0.3
url@1.0.4
useraccounts:core@1.8.1
useraccounts:semantic-ui@1.8.1
velocity:chokidar@0.12.6_1
velocity:core@0.6.0
velocity:html-reporter@0.5.3
velocity:meteor-internals@1.1.0_7
velocity:shim@0.1.0
webapp@1.2.0
webapp-hashing@1.0.3
yasaricli:slugify@0.0.5

**Comment by Deadly0** [comment]
+1 the same error. Package doesn't work on Windows.
@samhatoum can you help us run it on Windows?

**Comment by jirikrepl** [comment]
+1 Same error, Windows 8.1.

 In clean project, app is crashing. Just added xolvio:webdriver. 

    TypeError: Arguments to path.join must be strings
    ...
       at C:\Users\Jiri\Desktop\test\.meteor\local\build\programs\server\packages\xolvio_webdriver.js:435:3

**Comment by samhatoum** [comment]
Hey. This package is deprecated. You should use Chimp

**Comment by jirikrepl** [comment]
Thanks. I don't know why, but I couldn't find this page https://chimp.readme.io/docs/getting-started-mocha
